/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Create and manage website pages with flexible block-based layouts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Page title (20-100 chars) - displayed in browser tab and as the main heading
   */
  title: string;
  /**
   * URL-friendly identifier (e.g., "about-us" creates /about-us)
   */
  slug: string;
  /**
   * Build your page by adding content blocks
   */
  layout: (
    | {
        /**
         * Small text above headline (10-40 chars). e.g., "Discovery-First Product Management"
         */
        eyebrow?: string | null;
        /**
         * Main headline (20-60 chars). One sentence. Action-oriented. No jargon.
         */
        headline: string;
        /**
         * Word to highlight in brand color (3-20 chars). Must appear in headline.
         */
        headlineEmphasis?: string | null;
        /**
         * Supporting text (40-160 chars). Expands on headline. Plain English value prop.
         */
        subheadline: string;
        /**
         * Optional background image for the hero section
         */
        backgroundImage?: (number | null) | Media;
        /**
         * Primary button text (10-25 chars). e.g., "Start Free Trial"
         */
        primaryCtaText: string;
        /**
         * Primary button URL
         */
        primaryCtaUrl: string;
        /**
         * Secondary button text (10-25 chars). e.g., "See How It Works"
         */
        secondaryCtaText?: string | null;
        /**
         * Secondary button URL
         */
        secondaryCtaUrl?: string | null;
        /**
         * Trust signal below CTAs (10-40 chars). e.g., "No credit card required"
         */
        trustNote?: string | null;
        /**
         * Text alignment for the hero content
         */
        alignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Small text above heading (5-30 chars). e.g., "Our Approach"
         */
        eyebrow?: string | null;
        /**
         * Section heading (15-80 chars)
         */
        heading?: string | null;
        /**
         * Text below heading (30-160 chars)
         */
        subheading?: string | null;
        /**
         * Main content area - supports rich text formatting, links, and embedded media
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional image or media to accompany the content
         */
        media?: (number | null) | Media;
        /**
         * Accessibility description for the media (20-100 chars)
         */
        mediaAlt?: string | null;
        /**
         * Where the media appears relative to the text
         */
        mediaPosition?: ('above' | 'below' | 'left' | 'right') | null;
        /**
         * Content width setting
         */
        layout?: ('contained' | 'full' | 'narrow') | null;
        /**
         * Section background color
         */
        backgroundColor?: ('default' | 'light-gray' | 'dark' | 'brand-light') | null;
        /**
         * Text alignment (heading and content)
         */
        textAlign?: ('left' | 'center') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richContent';
      }
    | {
        /**
         * Visual style. Use "Final" for page-ending CTAs, "Mid-Page" for inline CTAs.
         */
        variant?: ('standard' | 'final' | 'mid') | null;
        /**
         * Display large logo mark above headline (recommended for Final variant)
         */
        showLogoMark?: boolean | null;
        /**
         * CTA headline (15-60 chars). e.g., "Build Products Customers Actually Want"
         */
        headline: string;
        /**
         * Supporting text (30-100 chars). e.g., "Start with evidence. Ship with confidence."
         */
        subheadline?: string | null;
        /**
         * Primary button (10-25 chars). e.g., "Start Free Trial"
         */
        primaryCtaText: string;
        /**
         * Primary button URL
         */
        primaryCtaUrl: string;
        /**
         * Secondary button (10-25 chars). e.g., "Book a Demo"
         */
        secondaryCtaText?: string | null;
        /**
         * Secondary button URL
         */
        secondaryCtaUrl?: string | null;
        /**
         * Friction reducers below buttons (3-5 recommended). e.g., "No credit card required"
         */
        trustSignals?:
          | {
              /**
               * 10-40 characters
               */
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background color. Use "Brand Primary" for final CTAs.
         */
        backgroundColor?: ('default' | 'brand-primary' | 'brand-secondary' | 'dark' | 'light') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        /**
         * Type of social proof to display
         */
        variant?: ('quotes' | 'metrics' | 'logos') | null;
        /**
         * Section headline (15-60 chars). e.g., "Teams Who've Made the Shift"
         */
        headline?: string | null;
        /**
         * Optional intro text (30-120 chars)
         */
        subheadline?: string | null;
        /**
         * Customer testimonials (1-4). Quality over quantity.
         */
        quotes?:
          | {
              /**
               * The testimonial text (60-250 chars). Must include specific outcome.
               */
              quote: string;
              /**
               * Full name (5-50 chars)
               */
              authorName: string;
              /**
               * Role and company (10-60 chars). e.g., "VP Product at Acme Corp"
               */
              authorTitle: string;
              /**
               * Headshot photo (increases trust significantly)
               */
              authorImage?: (number | null) | Media;
              /**
               * Company logo (optional)
               */
              companyLogo?: (number | null) | Media;
              /**
               * Star rating 1-5 (optional)
               */
              rating?: number | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Headline metrics (2-4)
         */
        metrics?:
          | {
              /**
               * The metric value (1-15 chars). e.g., "40%", "3x", "12 weeks"
               */
              value: string;
              /**
               * What it measures (15-60 chars). e.g., "reduction in roadmap debates"
               */
              label: string;
              /**
               * Optional context (20-80 chars). e.g., "average across all customers"
               */
              context?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Company logos (3-12). Grayscale preferred.
         */
        logos?:
          | {
              /**
               * Company logo
               */
              logo: number | Media;
              /**
               * Company name for accessibility (5-40 chars)
               */
              companyName: string;
              /**
               * Optional link to case study or website
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * How items are displayed
         */
        layout?: ('grid' | 'carousel' | 'stacked') | null;
        /**
         * Section background color
         */
        backgroundColor?: ('default' | 'light-gray' | 'dark') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'socialProof';
      }
    | {
        /**
         * Small text above heading (5-30 chars). e.g., "Why Choose Us"
         */
        eyebrow?: string | null;
        /**
         * Section heading (15-60 chars). e.g., "Everything You Need, Nothing You Don't"
         */
        heading?: string | null;
        /**
         * Intro text below heading (30-120 chars)
         */
        subheading?: string | null;
        /**
         * Number of features per row on desktop
         */
        columns?: ('2' | '3' | '4') | null;
        /**
         * Feature items (2-12)
         */
        features: {
          /**
           * Icon from approved set
           */
          icon?:
            | (
                | 'check'
                | 'star'
                | 'shield'
                | 'lightning'
                | 'chart'
                | 'users'
                | 'target'
                | 'puzzle'
                | 'layers'
                | 'compass'
                | 'inbox'
                | 'signal'
              )
            | null;
          /**
           * Custom image instead of icon (optional)
           */
          image?: (number | null) | Media;
          /**
           * Feature title (10-50 chars)
           */
          title: string;
          /**
           * One-line value prop (15-60 chars). e.g., "Turn noise into signal"
           */
          tagline?: string | null;
          /**
           * Feature description (40-150 chars)
           */
          description: string;
          /**
           * Optional "Learn more" link URL
           */
          link?: string | null;
          /**
           * Link text (10-25 chars). e.g., "Explore →"
           */
          linkText?: string | null;
          id?: string | null;
        }[];
        /**
         * Section background color
         */
        backgroundColor?: ('default' | 'light-gray' | 'brand-light') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'features';
      }
    | {
        /**
         * Optional section heading
         */
        heading?: string | null;
        /**
         * The main content area - supports rich text formatting
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional image to accompany the text
         */
        image?: (number | null) | Media;
        /**
         * Where the image appears relative to the text
         */
        imagePosition?: ('left' | 'right' | 'above' | 'below') | null;
        /**
         * Background color for this section
         */
        backgroundColor?: ('white' | 'light-gray' | 'brand-primary' | 'brand-secondary') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textContent';
      }
  )[];
  meta?: {
    /**
     * SEO title (50-60 chars) - if empty, page title will be used
     */
    title?: string | null;
    /**
     * Meta description for search engines (150-160 chars)
     */
    description?: string | null;
    /**
     * Image for social media sharing (Open Graph / Twitter Card)
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines
     */
    noIndex?: boolean | null;
  };
  /**
   * Page visibility status
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * When this page should go live
   */
  publishedAt?: string | null;
  /**
   * Page layout template
   */
  template?: ('default' | 'full-width' | 'sidebar' | 'landing') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              headlineEmphasis?: T;
              subheadline?: T;
              backgroundImage?: T;
              primaryCtaText?: T;
              primaryCtaUrl?: T;
              secondaryCtaText?: T;
              secondaryCtaUrl?: T;
              trustNote?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              content?: T;
              media?: T;
              mediaAlt?: T;
              mediaPosition?: T;
              layout?: T;
              backgroundColor?: T;
              textAlign?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              variant?: T;
              showLogoMark?: T;
              headline?: T;
              subheadline?: T;
              primaryCtaText?: T;
              primaryCtaUrl?: T;
              secondaryCtaText?: T;
              secondaryCtaUrl?: T;
              trustSignals?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        socialProof?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorTitle?: T;
                    authorImage?: T;
                    companyLogo?: T;
                    rating?: T;
                    id?: T;
                  };
              metrics?:
                | T
                | {
                    value?: T;
                    label?: T;
                    context?: T;
                    id?: T;
                  };
              logos?:
                | T
                | {
                    logo?: T;
                    companyName?: T;
                    url?: T;
                    id?: T;
                  };
              layout?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              columns?: T;
              features?:
                | T
                | {
                    icon?: T;
                    image?: T;
                    title?: T;
                    tagline?: T;
                    description?: T;
                    link?: T;
                    linkText?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        textContent?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  status?: T;
  publishedAt?: T;
  template?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}