/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Create and manage website pages with flexible block-based layouts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The page title - displayed in browser tab and as the main heading
   */
  title: string;
  /**
   * URL-friendly identifier (e.g., "about-us" creates /about-us)
   */
  slug: string;
  /**
   * Build your page by adding content blocks
   */
  layout: (
    | {
        /**
         * The main headline for this section
         */
        heading: string;
        /**
         * Supporting text that appears below the heading
         */
        subheading?: string | null;
        /**
         * Optional background image for the hero section
         */
        backgroundImage?: (number | null) | Media;
        /**
         * Add up to 2 CTA buttons
         */
        ctaButtons?:
          | {
              label: string;
              /**
               * URL or path (e.g., /contact or https://example.com)
               */
              link: string;
              variant?: ('primary' | 'secondary' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Text alignment for the hero content
         */
        alignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Optional section heading
         */
        heading?: string | null;
        /**
         * The main content area - supports rich text formatting
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional image to accompany the text
         */
        image?: (number | null) | Media;
        /**
         * Where the image appears relative to the text
         */
        imagePosition?: ('left' | 'right' | 'above' | 'below') | null;
        /**
         * Background color for this section
         */
        backgroundColor?: ('white' | 'light-gray' | 'brand-primary' | 'brand-secondary') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textContent';
      }
    | {
        /**
         * Visual style of the CTA section
         */
        style?: ('banner' | 'card' | 'minimal') | null;
        /**
         * Main CTA headline (e.g., "Ready to get started?")
         */
        heading: string;
        /**
         * Supporting text for the CTA
         */
        description?: string | null;
        buttons: {
          /**
           * Button text (e.g., "Start Free Trial")
           */
          label: string;
          /**
           * URL or path for the button
           */
          link: string;
          variant?: ('primary' | 'secondary' | 'outline') | null;
          /**
           * Open link in a new browser tab
           */
          openInNewTab?: boolean | null;
          id?: string | null;
        }[];
        backgroundColor?: ('brand-primary' | 'brand-secondary' | 'dark' | 'light') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        /**
         * Section heading (e.g., "Why choose us?")
         */
        heading?: string | null;
        /**
         * Optional intro text below the heading
         */
        subheading?: string | null;
        /**
         * Number of features per row on desktop
         */
        columns?: ('2' | '3' | '4') | null;
        /**
         * Add feature items to display in the grid
         */
        features: {
          /**
           * Icon name (e.g., "check", "star", "shield") - we'll map these to actual icons
           */
          icon?: string | null;
          /**
           * Or use a custom image instead of an icon
           */
          image?: (number | null) | Media;
          title: string;
          description: string;
          /**
           * Optional link for "Learn more"
           */
          link?: string | null;
          id?: string | null;
        }[];
        backgroundColor?: ('white' | 'light-gray' | 'brand-light') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'features';
      }
  )[];
  meta?: {
    /**
     * SEO title - if empty, page title will be used. Recommended: 50-60 characters
     */
    title?: string | null;
    /**
     * Meta description for search engines. Recommended: 150-160 characters
     */
    description?: string | null;
    /**
     * Image for social media sharing (Open Graph / Twitter Card)
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines
     */
    noIndex?: boolean | null;
  };
  /**
   * Page visibility status
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * When this page should go live
   */
  publishedAt?: string | null;
  /**
   * Page layout template
   */
  template?: ('default' | 'full-width' | 'sidebar' | 'landing') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaButtons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        textContent?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              style?: T;
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              subheading?: T;
              columns?: T;
              features?:
                | T
                | {
                    icon?: T;
                    image?: T;
                    title?: T;
                    description?: T;
                    link?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  status?: T;
  publishedAt?: T;
  template?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}